# Generated by Django 4.0.4 on 2023-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication',
            new_name='publications',
        ),
    ]
